export const TYPE_USER_DATA_REQUEST = '@user/USER_DATA_REQUEST';
export const TYPE_USER_DATA_SUCCESS = '@user/USER_DATA_SUCCESS';
export const TYPE_USER_DATA_FAILURE = '@user/USER_DATA_FAILURE';

export const TYPE_USER_REPOS_REQUEST = '@user/USER_REPOS_REQUEST';
export const TYPE_USER_REPOS_SUCCESS = '@user/USER_REPOS_SUCCESS';
export const TYPE_USER_REPOS_FAILURE = '@user/USER_REPOS_FAILURE';
