export const TYPE_USER_REQUEST = '@user/USER_REQUEST';
export const TYPE_USER_SUCCESS = '@user/USER_SUCCESS';
export const TYPE_USER_FAILURE = '@user/USER_FAILURE';
export const TYPE_USER_LOADING = '@user/USER_LOADING';
export const TYPE_USER_CLEAN_STATES = '@user/USER_CLEAN_STATES';

export const TYPE_REPOS_REQUEST = '@repos/REPOS_REQUEST';
export const TYPE_REPOS_SUCCESS = '@repos/REPOS_SUCCESS';
export const TYPE_REPOS_FAILURE = '@repos/REPOS_FAILURE';
export const TYPE_REPOS_LOADING = '@repos/REPOS_LOADING';
export const TYPE_REPOS_SET_DISPLAY = '@repos/SET_DISPLAY_REPOS';
export const TYPE_REPOS_CLEAN_STATES = '@repos/REPOS_CLEAN_STATES';
export const TYPE_REPOS_FILTER_REPOS = '@repos/REPOS_FILTER_REPOS';

export const TYPE_REPOS_STARRED_REQUEST = '@repos/REPOS_STARRED_RREQUEST';
export const TYPE_REPOS_STARRED_SUCCESS = '@repos/REPOS_STARRED_RSUCCESS';
export const TYPE_REPOS_STARRED_FAILURE = '@repos/REPOS_STARRED_RFAILURE';

export const TYPE_REPOS_SEARCH_REQUEST = '@repos/REPOS_SEARCH_REQUEST';
export const TYPE_REPOS_SEARCH_SUCCESS = '@repos/REPOS_SEARCH_SUCCESS';
export const TYPE_REPOS_SEARCH_FAILURE = '@Trepos/REPOS_SEARCH_FAILURE';
